-- 코드를 입력하세요
SELECT AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(sales*price) as TOTAL_SALES
FROM BOOK NATURAL JOIN BOOK_SALES NATURAL JOIN AUTHOR
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID,CATEGORY DESC