-- 코드를 입력하세요
#기본적으로 distinct
SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
PRODUCT_ID,USER_ID,SALES_AMOUNT
from ONLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
PRODUCT_ID,NULL,SALES_AMOUNT
from OFFLINE_SALE
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3

ORDER BY 1,2,3 ASC


#ON ONLINE_SALE.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID