-- 코드를 입력하세요

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * ((100-P.DISCOUNT_RATE)/100),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
ON C.CAR_ID = H.CAR_ID LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE ('2022-11-01 00:00:00' BETWEEN START_DATE AND END_DATE)
OR ('2022-11-30 00:00:00' BETWEEN START_DATE AND END_DATE))
AND C.CAR_TYPE IN('세단', 'SUV')
AND P.DURATION_TYPE = '30일 이상'
GROUP BY C.CAR_ID, C.CAR_TYPE
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC


