SELECT ID, 
CASE
 WHEN A.RANKS <= B.CNT/4 THEN 'CRITICAL'
 WHEN A.RANKS <= B.CNT/2 THEN 'HIGH'
 WHEN A.RANKS <= B.CNT/4*3 THEN 'MEDIUM'
 ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKS
FROM ECOLI_DATA) A INNER JOIN (SELECT COUNT(*) AS CNT FROM ECOLI_DATA AS CNT) AS B
ORDER BY ID;