
SELECT A.CAR_ID, ROUND(AVG(AVGERAGE_DURATION),1) AS AVGERAGE_DURATION
FROM (
SELECT HISTORY_ID,CAR_ID,DATEDIFF(END_DATE,START_DATE)+1 AS AVGERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS A 
GROUP BY A.CAR_ID
HAVING AVG(AVGERAGE_DURATION) >= 7
ORDER BY AVGERAGE_DURATION DESC, A.CAR_ID DESC