SELECT
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) * 1.0 / T.TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
JOIN (
    SELECT COUNT(*) AS TOTAL_USERS
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS T ON 1 = 1
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), T.TOTAL_USERS
ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE);