SELECT  
    TBL.YEAR, 
    TBL.MONTH, 
    COUNT(DISTINCT TBL.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT TBL.USER_ID) / TOTAL_USERS.TOTALCNT, 1) AS PURCHASED_RATIO
FROM (
    SELECT 
        YEAR(S.SALES_DATE) AS YEAR, 
        MONTH(S.SALES_DATE) AS MONTH,
        S.USER_ID
    FROM ONLINE_SALE S
    JOIN USER_INFO U ON S.USER_ID = U.USER_ID
    WHERE YEAR(U.JOINED) = 2021
) AS TBL,
(
    SELECT COUNT(*) AS TOTALCNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) AS TOTAL_USERS
WHERE TBL.YEAR IS NOT NULL AND TBL.MONTH IS NOT NULL
GROUP BY TBL.YEAR, TBL.MONTH, TOTAL_USERS.TOTALCNT
ORDER BY TBL.YEAR, TBL.MONTH;
