# -- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, B.MCDP_CD AS MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT A NATURAL JOIN APPOINTMENT B INNER JOIN DOCTOR C ON B.MDDR_ID = C.DR_ID
WHERE B.MCDP_CD = 'CS' AND B.APNT_CNCL_YN = 'N' 
AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD