-- 코드를 입력하세요

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW NATURAL JOIN MEMBER_PROFILE
WHERE MEMBER_ID = (
SELECT MEMBER_ID
FROM MEMBER_PROFILE NATURAL JOIN REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(REST_ID) DESC
LIMIT 1 )
ORDER BY REVIEW_DATE, REVIEW_TEXT 