-- 코드를 작성해주세요
SELECT ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO NATURAL JOIN (
SELECT ITEM_TREE.ITEM_ID 
FROM ITEM_TREE INNER JOIN ITEM_INFO
ON ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
WHERE ITEM_INFO.RARITY = 'RARE' ) AS B 
ORDER BY ITEM_ID DESC