-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A INNER JOIN 
(SELECT B.ITEM_ID
FROM (SELECT *
FROM ITEM_INFO
WHERE RARITY = 'RARE') AS A INNER JOIN ITEM_TREE AS B ON A.ITEM_ID = B.PARENT_ITEM_ID) AS B 
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC

