-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
WHERE (FISH_TYPE, LENGTH) IN (SELECT FISH_TYPE,MAX(LENGTH)
                          FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
                          GROUP BY FISH_TYPE 
                          )
                          
# SELECT I.ID, N.FISH_NAME, I.LENGTH
# FROM FISH_INFO AS I
# JOIN FISH_NAME_INFO AS N 
# ON I.FISH_TYPE = N.FISH_TYPE
# WHERE (I.FISH_TYPE, I.LENGTH) IN
# (
#     SELECT FISH_TYPE, MAX(LENGTH)
#     FROM FISH_INFO
#     GROUP BY FISH_TYPE
# )
# ORDER BY I.ID ASC;