-- 코드를 작성해주세요

SELECT B.SCORE AS SCORE, A.EMP_NO AS EMP_NO,A.EMP_NAME AS EMP_NAME, A.POSITION AS POSITION, A.EMAIL AS EMAIL
FROM HR_EMPLOYEES A INNER JOIN
(SELECT SUM(SCORE) AS SCORE,EMP_NO
FROM HR_GRADE
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1 ) B ON A.EMP_NO = B.EMP_NO
