-- 코드를 입력하세요
SELECT
A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM 
(SELECT *
FROM USED_GOODS_BOARD 
WHERE CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31')AS A INNER JOIN USED_GOODS_REPLY AS B 
ON A.BOARD_ID = B.BOARD_ID
ORDER BY CREATED_DATE, A.TITLE

