-- 코드를 입력하세요
SELECT CATEGORY, SUM(TOTAL_SALE) AS TOTAL_SALES
FROM (SELECT CATEGORY , SUM(SALES) AS TOTAL_SALE
FROM BOOK_SALES NATURAL JOIN BOOK
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1 
GROUP BY BOOK_ID
ORDER BY CATEGORY) AS B 
GROUP BY CATEGORY
ORDER BY CATEGORY 
