-- 코드를 작성해
SELECT COUNT(*) AS FISH_COUNT,MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT ID,FISH_TYPE,IF(LENGTH<=10 OR NULL, 10,LENGTH) AS LENGTH,TIME FROM
FISH_INFO) AS A
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE